<script>
    /*
        can't send a real 404 response because
        by the time the browser realizes this
        it's already received the app as a 200.
        but the inference is gathered.

        (plus there *is* a 404 generated by the
        API's xhr response, and if you're poking
        around in devtools enough to notice the
        discrepancy, you'll probably understand
        why it's happening.)
    */
</script>

<svelte:head>
    <meta name="robots" content="noindex">
</svelte:head>

<div class="notFound">
    <div class="error">
        404
    </div>
    <div class="explain">
        There’s nothing here…
    </div>
</div>

<style>
    .notFound {
        text-align: center;
        opacity: 0.5;

        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }

    .error {
        font-size: 300px;
    }

    .explain {
        font-size: 50px;
    }
</style>
