name: automated backend tests

on: push

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        extensions: imagick
        ini-values: "error_reporting=E_ERROR|E_WARNING|E_PARSE,upload_max_filesize=100M,post_max_size=100M,max_execution_time=300"
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install prerequisites
      run: |
        sudo apt-get update -y
        sudo apt-get install exiftool ffmpeg
        python -m pip install --upgrade pip
        pip install -r ./test/requirements.txt
    - name: Build distribution for functional test
      run: ./scripts/build_dist.sh
    - name: Run functional tests
      env:
        POZZO_DIST: 1
      run: cd test && pytest
    - name: Rebuild distribution for coverage test
      env:
        POZZO_CODE_COVERAGE: 1
      run: ./scripts/build_dist.sh
    - name: Generate coverage data
      env:
        POZZO_DIST: 1
        POZZO_CODE_COVERAGE: 1
      run: |
        cd test
        pytest
        mv ../dist/test/tools/raw_coverage ./tools/
        ./tools/calculate_coverage.sh
    - name: Upload coverage data
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        bash <(curl -s https://codecov.io/bash) -f test/tools/output/coverage.xml -t $CODECOV_TOKEN


